import React, { useState } from "react";
import { SlidersHorizontal, PlayCircle, TrendingUp } from "lucide-react";

const Simulation = () => {
  const [scenario, setScenario] = useState({
    marketingIncrease: 0,
    competitorPrice: 0,
    season: "",
  });

  const [result, setResult] = useState(null);

  const handleChange = (e) => {
    setScenario({
      ...scenario,
      [e.target.name]: e.target.value,
    });
  };

  const runSimulation = () => {
    // Fake simulation calculation
    const predictedSales =
      50000 +
      Number(scenario.marketingIncrease) * 200 +
      Number(scenario.competitorPrice) * 50;

    setResult(predictedSales);
  };

  return (
    <div className="min-h-screen">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-800">
          Scenario Simulator
        </h1>
        <p className="text-sm text-gray-500">
          Test "what-if" scenarios by adjusting business variables and see the
          predicted impact generated by the trained AI model.
        </p>
      </div>

      {/* Simulation Controls */}
      <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
        <div className="flex items-center gap-2 mb-6">
          <SlidersHorizontal size={20} className="text-gray-600" />
          <h3 className="text-lg font-semibold text-gray-800">
            Scenario Inputs
          </h3>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {/* Marketing Increase */}
          <div>
            <label className="text-sm text-gray-600 mb-2 block">
              Marketing Budget Increase (%)
            </label>
            <input
              type="number"
              name="marketingIncrease"
              value={scenario.marketingIncrease}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 text-sm outline-none"
              placeholder="Example: 20"
            />
          </div>

          {/* Competitor Price */}
          <div>
            <label className="text-sm text-gray-600 mb-2 block">
              Competitor Price
            </label>
            <input
              type="number"
              name="competitorPrice"
              value={scenario.competitorPrice}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 text-sm outline-none"
              placeholder="Example: 40"
            />
          </div>

          {/* Season */}
          <div>
            <label className="text-sm text-gray-600 mb-2 block">Season</label>
            <select
              name="season"
              value={scenario.season}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 text-sm outline-none"
            >
              <option value="">Select season</option>
              <option value="summer">Summer</option>
              <option value="winter">Winter</option>
              <option value="spring">Spring</option>
            </select>
          </div>
        </div>

        {/* Run Simulation */}
        <div className="mt-6">
          <button
            onClick={runSimulation}
            className="flex items-center gap-2 bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition"
          >
            <PlayCircle size={18} />
            Run Simulation
          </button>
        </div>
      </div>

      {/* Result */}
      {result && (
        <div className="bg-white rounded-xl shadow-sm p-6 flex items-center gap-4">
          <div className="bg-green-100 p-3 rounded-lg">
            <TrendingUp className="text-green-600" size={22} />
          </div>

          <div>
            <p className="text-sm text-gray-500">Simulated Sales Prediction</p>
            <h2 className="text-2xl font-semibold text-gray-800">
              {result.toLocaleString()} units
            </h2>
          </div>
        </div>
      )}

      {/* Info */}
      <div className="mt-6 bg-white p-4 rounded-lg shadow-sm">
        <p className="text-sm text-gray-500">
          The simulator estimates potential outcomes based on the trained model.
          Adjust the inputs above to explore different business scenarios and
          understand how they may influence predictions.
        </p>
      </div>
    </div>
  );
};

export default Simulation;
